language: python
python:
    - 2.7
    - 3.3
   

cache: apt
before_install:
   - until sudo add-apt-repository -y ppa:saiarcot895/chromium-beta; do echo retry; done
   - until sudo add-apt-repository --yes ppa:kalakris/cmake; do echo retry; done
   - until sudo apt-get -qq update; do echo retry; done 
   - until sudo apt-get install cmake; do echo retry; done
   
install:
  - export LZ="$TRAVIS_BUILD_DIR/../zus"
  - mkdir -p $LZ
  - wget --output-document=zustre.tar.gz  https://www.dropbox.com/s/wqvh31085s49ia4/zustre.tar.gz?dl=1;
  - tar xvf zustre.tar.gz --strip-components=1 -C $LZ;
  - ls $LZ

script:
  - mkdir -p build
  - cd build
  - mkdir run
  - cp -r $LZ/* run
  - ls run
  - /usr/bin/cmake -DLUSTREC_EXECUTABLE=run -DZ3_ROOT=run -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_PROGRAM_PATH=/usr/bin  -DCMAKE_INSTALL_PREFIX=run ../;

after_failure: "cat /home/travis/build/seahorn/seahorn/build/llvm-prefix/src/llvm-stamp/llvm-build-*.log"

after_script:
  - /usr/bin/cmake --build . > ./build.log 2>&1
  - /usr/bin/cmake --build . --target install > ./build.log 2>&1
  - cd ..
  - ls build/run/bin
  - ./build/run/bin/zustre -h



notifications:
  email:
    recipients:
     - zustre-build@googlegroups.com
    on_success: always
    on_failure: always